### ISSUE TITLE
Multi system prompts support

### ISSUE THREAD

**Issue by zekunzhao** [rayleizhu/vllm-ra#4]
Hi @rayleizhu,

I check the script [examples/relay_inference.py](https://github.com/rayleizhu/vllm-ra/blob/main/examples/relay_inference.py), and want to inference with your method with multiple systems prompts and each of them with multiple questions.

For example:  
[
"I am Chris. Who are you ?"
"I am Chris. What can you do ?"
"I am Jack. What's your name ?"
"I am Jack. There is a llama in my garden, what should I do ?"
]

Can we get the result with just a one-time inference with your method? 
I tried the following format, but it does not generate the correct outputs.

system_prompt =  [  "I am Chris.", "I am Jack."  ]
prompts = [
    "Who are you ?",
    "What can you do ?",
    "What's your name ?",
    "There is a llama in my garden. What should I do ?"
]

Thanks!

**Comment by rayleizhu** [comment]
Currently it is not supported. It needs a fused operator to for hybrid batch with multiple sharing groups. I’m unsure whether I have time to write such an extension.

If you have some sense on CUDA and want to collaborate for an extended version of RelayAttention, please let me know.

On 6 Dec 2024, at 8:49 AM, zekun ***@***.***> wrote:



Hi @rayleizhu<https://github.com/rayleizhu>,

I check the script examples/relay_inference.py<https://github.com/rayleizhu/vllm-ra/blob/main/examples/relay_inference.py>, and want to inference with your method with multiple systems prompts and each of them with multiple questions.

For example:
[
"I am Chris. Who are you ?"
"I am Chris. What can you do ?"
"I am Jack. What's your name ?"
"I am Jack. There is a llama in my garden, what should I do ?"
]

Can we get the result with just a one-time inference with your method?
I tried the following format, but it does not generate the correct outputs.

system_prompt = [ "I am Chris.", "I am Jack." ]
prompts = [
"Who are you ?",
"What can you do ?",
"What's your name ?",
"There is a llama in my garden. What should I do ?"
]

Thanks!
